version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///data/network_monitoring.db
      - SECRET_KEY=${SECRET_KEY}
      - MONITORING_INTERVAL=${MONITORING_INTERVAL:-30}
      - EMAIL_ENABLED=${EMAIL_ENABLED:-false}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    volumes:
      - monitoring-data:/app/data
      - monitoring-logs:/app/logs
    restart: unless-stopped
    networks:
      - monitoring-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Reverse proxy pour la production (optionnel)
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    networks:
      - monitoring-network
    profiles:
      - production

networks:
  monitoring-network:
    driver: bridge

volumes:
  monitoring-data:
    driver: local
  monitoring-logs:
    driver: local
