name: Performance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  performance-test:
    name: Performance Testing
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install locust

    - name: Create test environment
      run: |
        cat > .env << EOF
        SECRET_KEY=test-secret-key
        DATABASE_URL=sqlite:///test_performance.db
        MONITORING_INTERVAL=60
        EMAIL_ENABLED=false
        EOF

    - name: Start application for testing
      run: |
        python run.py &
        sleep 10
      env:
        FLASK_ENV: production

    - name: Run basic performance test
      run: |
        # Test simple de charge
        curl -f http://localhost:5000 || exit 1
        
        # Test de performance avec curl
        for i in {1..10}; do
          curl -s -w "%{time_total}\n" -o /dev/null http://localhost:5000
        done

    - name: Check application logs
      run: |
        echo "Application is running, basic performance test completed"
