name: Security Scan

on:
  schedule:
    # Exécuter tous les lundi à 2h du matin
    - cron: '0 2 * * 1'
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  trivy-scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner (filesystem)
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-fs-results.sarif'

    - name: Upload Trivy filesystem scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-fs-results.sarif'
        category: 'trivy-filesystem'

  docker-security-scan:
    name: Docker Image Security Scan
    runs-on: ubuntu-latest
    needs: trivy-scan
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image for scanning
      run: |
        docker build -t network-monitoring:scan .

    - name: Run Trivy vulnerability scanner (Docker image)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'network-monitoring:scan'
        format: 'sarif'
        output: 'trivy-docker-results.sarif'

    - name: Upload Trivy Docker scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-docker-results.sarif'
        category: 'trivy-docker'

  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install safety
      run: pip install safety

    - name: Check Python dependencies for security vulnerabilities
      run: |
        pip install -r requirements.txt
        safety check --json --output safety-report.json || true

    - name: Upload safety results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: safety-report
        path: safety-report.json
